#!/usr/bin/env bash
# display hours from 0 to 12 and display minutes from 1 to 59

hour=0
minute=0

while [[ $hour -lt 13 ]]; do
  echo "Hour: $hour"
  while [[ $minute -lt 60 ]]; do
    echo "$minute"
    ((minute++))
  done
  minute=0
  ((hour++))
done
